<%@page import="bloodbank.ConnectionProvider"%>
<%@page import="java.sql.*"%>
<%@page import="java.sql.*,bloodbank.*" %>
<html>
<body>

<% 
try
{
Connection con=ConnectionProvider.getConnection();
Statement st=con.createStatement();
String q1="CREATE TABLE BLOODBANK_BANK(NAME VARCHAR2(40),ADDRESS VARCHAR2(400),CITY VARCHAR2(40),STATE VARCHAR2(40),AREA VARCHAR2(40),CONTACT VARCHAR2(11),EMAIL VARCHAR2(40) PRIMARY KEY,PASSWORD VARCHAR2(40),STATUS VARCHAR2(10))";
String q2="CREATE TABLE BLOODBANK_DONOR(NAME VARCHAR2(40),AGE VARCHAR2(5),CONTACT VARCHAR2(10),EMAIL VARCHAR2(40),PASSWORD VARCHAR2(40),GENDER VARCHAR2(10),ADDRESS VARCHAR2(400),BLOOD_GROUP VARCHAR2(10),STATUS VARCHAR2(10),IMAGEPATH VARCHAR2(400),CONSTRAINT BLOODBANK_DONOR_PK PRIMARY KEY (EMAIL) ENABLE)";
String q3="CREATE TABLE BLOODBANK_FEEDBACK(NAME VARCHAR2(40),EMAIL VARCHAR2(40),CONTACT VARCHAR2(10),USERCOMMENT VARCHAR2(400),CONSTRAINT BLOODBANK_FEEDBACK_PK PRIMARY KEY (EMAIL) ENABLE)";
st.execute(q1);
st.execute(q2);
st.execute(q3);
System.out.println("Table created");
con.close();
}catch(Exception e)
{
System.out.println(e);	
}
%>
</body>
</html>